// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/concerts": {
    params: {};
  };
  "/concerts/:city": {
    params: {
      "city": string;
    };
  };
  "/concerts/trending": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/users/new": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/auth/login" | "/auth/register" | "/concerts" | "/concerts/:city" | "/concerts/trending" | "/users" | "/users/:userId" | "/users/new" | "/*";
  };
  "./pages/Home/index.tsx": {
    id: "pages/Home/index";
    page: "/";
  };
  "./pages/About/index.tsx": {
    id: "pages/About/index";
    page: "/about";
  };
  "./pages/Auth/AuthLayout.tsx": {
    id: "pages/Auth/AuthLayout";
    page: "/auth/login" | "/auth/register";
  };
  "./pages/Auth/Login.tsx": {
    id: "pages/Auth/Login";
    page: "/auth/login";
  };
  "./pages/Auth/Register.tsx": {
    id: "pages/Auth/Register";
    page: "/auth/register";
  };
  "./pages/Concerts/ConcertsLayout.tsx": {
    id: "pages/Concerts/ConcertsLayout";
    page: "/concerts" | "/concerts/:city" | "/concerts/trending";
  };
  "./pages/Concerts/ConcertsHome.tsx": {
    id: "pages/Concerts/ConcertsHome";
    page: "/concerts";
  };
  "./pages/Concerts/City.tsx": {
    id: "pages/Concerts/City";
    page: "/concerts/:city";
  };
  "./pages/Concerts/Trending.tsx": {
    id: "pages/Concerts/Trending";
    page: "/concerts/trending";
  };
  "./pages/User/UserList.tsx": {
    id: "pages/User/UserList";
    page: "/users";
  };
  "./pages/User/UserDetail.tsx": {
    id: "pages/User/UserDetail";
    page: "/users/:userId";
  };
  "./pages/User/NewUser.tsx": {
    id: "pages/User/NewUser";
    page: "/users/new";
  };
  "./pages/NotFound/index.tsx": {
    id: "pages/NotFound/index";
    page: "/*";
  };
};